import { useState } from 'react';
import { partnersService } from '../../services/member3Service.js';
import { EmptyState, ErrorText, Field, Loading, PageHeading, Panel, getRows, useAsyncAction } from '../../components/Member3UI.jsx';

export default function JVPartnerDirectory() {
  const [tenderId, setTenderId] = useState(''); const [rows, setRows] = useState([]); const [searched, setSearched] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(null); const [showForm, setShowForm] = useState(false); const action = useAsyncAction();
  async function search(event) { event.preventDefault(); if (!tenderId.trim()) return; setLoading(true); setError(null); setSearched(true); try { setRows(getRows(await partnersService.list(tenderId.trim()))); } catch (e) { setError(e); } finally { setLoading(false); } }
  async function publish(event) { event.preventDefault(); const fd = new FormData(event.currentTarget); const data = Object.fromEntries(fd.entries()); const result = await action.run(() => partnersService.publish(tenderId.trim(), data)); if (result !== undefined) { setShowForm(false); await search(new Event('submit')); } }
  return <>
    <PageHeading eyebrow="BUSINESS WORKSPACE" title="JV & consortium partners" description="Find companies interested in collaborating on a specific tender." action={<button className="button button-primary" onClick={() => setShowForm(v => !v)} disabled={!tenderId.trim()}>{showForm ? 'Close form' : 'List your interest'}</button>} />
    <Panel title="Find partners for a tender" note="Enter the tender ID from the opportunity details page to view its partner directory.">
      <form className="inline-form" onSubmit={search}><Field label="Tender ID"><input value={tenderId} onChange={e => setTenderId(e.target.value)} placeholder="Paste tender ID" /></Field><button className="button button-primary" disabled={loading || !tenderId.trim()}>{loading ? 'Searching…' : 'Search partners'}</button></form>
      {error && <ErrorText error={error} />}{loading ? <Loading label="Finding partners…" /> : searched && rows.length === 0 ? <EmptyState icon="⌕" title="No partner listings yet">There are no companies listed for this tender. You can publish your own interest.</EmptyState> : null}
      {!searched && <div className="hint-card"><span className="hint-icon">↗</span><span>Open a tender’s details to copy its ID, then search for companies offering complementary capabilities.</span></div>}
      {rows.length > 0 && <div className="card-grid">{rows.map(row => <article className="partner-card" key={row.id}><div className="partner-avatar">{(row.companyName || 'C').slice(0, 1).toUpperCase()}</div><div><h3>{row.companyName || 'Company'}</h3><p>{row.offeredCapabilities || 'Capabilities not provided'}</p></div><div className="partner-contact"><span>{row.contactPerson || 'Contact'}</span><a href={row.contactEmail ? `mailto:${row.contactEmail}` : undefined}>{row.contactEmail || 'No email supplied'}</a>{row.contactPhone && <a href={`tel:${row.contactPhone}`}>{row.contactPhone}</a>}</div></article>)}</div>}
    </Panel>
    {showForm && <Panel title="Publish your collaboration interest" note="Your company contact details will be visible to other businesses browsing this tender."><ErrorText error={action.error} /><form className="form-grid" onSubmit={publish}><Field label="Company name"><input name="companyName" required /></Field><Field label="Offered capabilities"><textarea name="offeredCapabilities" required rows="3" placeholder="What expertise, capacity, or certifications can you contribute?" /></Field><Field label="Contact person"><input name="contactPerson" required /></Field><Field label="Contact email"><input name="contactEmail" type="email" required /></Field><Field label="Contact phone"><input name="contactPhone" type="tel" /></Field><div className="form-actions"><button className="button button-primary" disabled={action.busy}>{action.busy ? 'Publishing…' : 'Publish listing'}</button></div></form></Panel>}
  </>;
}
