import { useEffect, useState } from 'react';
import { organizationService } from '../../services/member3Service.js';
import { EmptyState, ErrorText, Field, Loading, PageHeading, Panel, StatusPill, formatDate, getRows, useAsyncAction } from '../../components/Member3UI.jsx';

export default function OrgPortal() {
  const [tab, setTab] = useState('listings'); const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(null); const action = useAsyncAction();
  async function load() { setLoading(true); setLoadError(null); try { setRows(getRows(await organizationService.listMine())); } catch (e) { setLoadError(e); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function submit(event) { event.preventDefault(); const form = event.currentTarget; const data = Object.fromEntries(new FormData(form).entries()); data.estimatedValue = data.estimatedValue ? Number(data.estimatedValue) : null; data.submissionDeadline = data.submissionDeadline ? new Date(data.submissionDeadline).toISOString() : null; data.mandatoryDocuments = data.mandatoryDocuments.split('\n').map(x => x.trim()).filter(Boolean); const result = await action.run(() => organizationService.create(data)); if (result !== undefined) { form.reset(); setTab('listings'); await load(); } }
  return <>
    <PageHeading eyebrow="PRIVATE ORGANIZATION" title="Publishing portal" description="Create and manage procurement opportunities for suppliers." action={<button className="button button-primary" onClick={() => setTab('new')}>＋ New opportunity</button>} />
    <div className="tabs" role="tablist"><button className={tab === 'listings' ? 'tab active' : 'tab'} onClick={() => setTab('listings')} role="tab">My listings</button><button className={tab === 'new' ? 'tab active' : 'tab'} onClick={() => setTab('new')} role="tab">Create opportunity</button></div>
    {tab === 'listings' ? <Panel title="Your procurement listings" note="Review the status of opportunities published by your organization."><button className="button button-text refresh-inline" onClick={load}>↻ Refresh</button>{loadError && <ErrorText error={loadError} />}{loading ? <Loading label="Loading listings…" /> : rows.length === 0 ? <EmptyState icon="▤" title="No procurement listings">Create an opportunity to invite businesses to submit proposals.</EmptyState> : <div className="table-wrap"><table><thead><tr><th>Opportunity</th><th>Category</th><th>Deadline</th><th>Status</th><th>Created</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><strong>{row.title || 'Untitled opportunity'}</strong><small>{row.referenceNumber || row.id}</small></td><td>{row.category || '—'}</td><td>{formatDate(row.submissionDeadline)}</td><td><StatusPill tone={row.status === 'APPROVED' || row.status === 'PUBLISHED' ? 'green' : 'amber'}>{row.status || 'Pending review'}</StatusPill></td><td>{formatDate(row.createdAt)}</td></tr>)}</tbody></table></div>}</Panel> : <Panel title="Create a procurement opportunity" note="Submitted opportunities may require admin approval before publication."><ErrorText error={action.error} /><form className="form-grid" onSubmit={submit}><Field label="Title"><input name="title" required /></Field><Field label="Category"><input name="category" required placeholder="e.g. Construction, IT, Medical" /></Field><Field label="Procurement type"><select name="type" defaultValue="RFQ"><option>RFQ</option><option>RFP</option><option>VENDOR_REQUEST</option><option>SUPPLIER_PROCUREMENT</option></select></Field><Field label="Estimated value (₹)"><input name="estimatedValue" type="number" min="0" step="any" /></Field><Field label="Location"><input name="location" /></Field><Field label="Submission deadline"><input name="submissionDeadline" type="datetime-local" required /></Field><Field label="Minimum turnover (₹ lakhs)"><input name="minTurnover" type="number" min="0" step="any" /></Field><Field label="Minimum experience (years)"><input name="minExperienceYears" type="number" min="0" step="1" /></Field><Field label="Required documents" hint="Enter one document name per line."><textarea name="mandatoryDocuments" rows="4" placeholder="GST registration\nCompany profile" /></Field><Field label="Opportunity details"><textarea name="description" rows="4" /></Field><div className="form-actions"><button className="button button-primary" disabled={action.busy}>{action.busy ? 'Submitting…' : 'Submit for review'}</button></div></form></Panel>}
  </>;
}
