import { useEffect, useState } from 'react';
import { adminService } from '../../services/member3Service.js';
import { EmptyState, ErrorText, Loading, PageHeading, Panel, StatusPill, formatDate, getRows, useAsyncAction } from '../../components/Member3UI.jsx';

export default function AdminApprovals() {
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [selected, setSelected] = useState(null); const action = useAsyncAction();
  async function load() { setLoading(true); setError(null); try { setRows(getRows(await adminService.listApprovals())); } catch (e) { setError(e); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function decide(decision) { const result = await action.run(() => adminService.decide(selected.id, { decision })); if (result !== undefined) { setSelected(null); await load(); } }
  return <>
    <PageHeading eyebrow="ADMINISTRATION" title="Approval queue" description="Review organization and procurement submissions awaiting a decision." action={<button className="button button-secondary" onClick={load}>↻ Refresh</button>} />
    <div className="stat-grid compact-stats"><div className="stat-card"><span>Waiting for review</span><strong>{rows.length}</strong><small>Requests</small></div><div className="stat-card"><span>Organizations</span><strong>{rows.filter(r => (r.kind || r.type || '').toLowerCase().includes('org')).length}</strong><small>In queue</small></div><div className="stat-card"><span>Procurements</span><strong>{rows.filter(r => (r.kind || r.type || '').toLowerCase().includes('procurement')).length}</strong><small>In queue</small></div></div>
    <Panel title="Pending approvals" note="Review submitted details before approving or declining a request.">{error && <ErrorText error={error} />}{action.error && <ErrorText error={action.error} />}{loading ? <Loading label="Loading approval queue…" /> : rows.length === 0 ? <EmptyState icon="✓" title="Nothing waiting for review">New requests will appear here when they are submitted.</EmptyState> : <div className="table-wrap"><table><thead><tr><th>Submission</th><th>Type</th><th>Submitted by</th><th>Submitted</th><th>Status</th><th /></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><strong>{row.title || row.organizationName || row.businessName || 'Request'}</strong><small>{row.registrationNo || row.referenceNumber || row.id}</small></td><td>{row.kind || row.type || 'Organization'}</td><td>{row.contactPerson || row.email || '—'}</td><td>{formatDate(row.createdAt || row.submittedAt)}</td><td><StatusPill tone="amber">Pending</StatusPill></td><td><button className="button button-small button-secondary" onClick={() => setSelected(row)}>Review</button></td></tr>)}</tbody></table></div>}</Panel>
    {selected && <div className="modal-backdrop" role="presentation" onMouseDown={e => e.target === e.currentTarget && setSelected(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="review-title"><div className="modal-title"><div><div className="eyebrow">APPROVAL REVIEW</div><h2 id="review-title">{selected.title || selected.organizationName || selected.businessName || 'Review request'}</h2></div><button className="icon-button" onClick={() => setSelected(null)} aria-label="Close">×</button></div><dl className="detail-list">{Object.entries({Type: selected.kind || selected.type, 'Contact person': selected.contactPerson, Email: selected.email || selected.contactEmail, Phone: selected.contactPhone, 'Registration number': selected.registrationNo, 'Submitted': formatDate(selected.createdAt || selected.submittedAt)}).filter(([, value]) => value).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><div className="modal-actions"><button className="button button-secondary" onClick={() => setSelected(null)}>Close</button><button className="button button-danger" disabled={action.busy} onClick={() => decide('REJECT')}>Reject</button><button className="button button-primary" disabled={action.busy} onClick={() => decide('APPROVE')}>Approve</button></div></section></div>}
  </>;
}
